var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.getGlobal=function(a){a=["object"==typeof globalThis&&globalThis,a,"object"==typeof window&&window,"object"==typeof self&&self,"object"==typeof global&&global];for(var b=0;b<a.length;++b){var d=a[b];if(d&&d.Math==Math)return d}throw Error("Cannot find global object");};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.checkEs6ConformanceViaProxy=function(){try{var a={},b=Object.create(new $jscomp.global.Proxy(a,{get:function(d,c,f){return d==a&&"q"==c&&f==b}}));return!0===b.q}catch(d){return!1}};$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS=!1;$jscomp.ES6_CONFORMANCE=$jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS&&$jscomp.checkEs6ConformanceViaProxy();$jscomp.arrayIteratorImpl=function(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};
$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.ISOLATE_POLYFILLS=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,d){if(a==Array.prototype||a==Object.prototype)return a;a[b]=d.value;return a};$jscomp.IS_SYMBOL_NATIVE="function"===typeof Symbol&&"symbol"===typeof Symbol("x");$jscomp.TRUST_ES6_POLYFILLS=!$jscomp.ISOLATE_POLYFILLS||$jscomp.IS_SYMBOL_NATIVE;
$jscomp.polyfills={};$jscomp.propertyToPolyfillSymbol={};$jscomp.POLYFILL_PREFIX="$jscp$";var $jscomp$lookupPolyfilledValue=function(a,b){var d=$jscomp.propertyToPolyfillSymbol[b];if(null==d)return a[b];d=a[d];return void 0!==d?d:a[b]};$jscomp.polyfill=function(a,b,d,c){b&&($jscomp.ISOLATE_POLYFILLS?$jscomp.polyfillIsolated(a,b,d,c):$jscomp.polyfillUnisolated(a,b,d,c))};
$jscomp.polyfillUnisolated=function(a,b,d,c){d=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var f=a[c];if(!(f in d))return;d=d[f]}a=a[a.length-1];c=d[a];b=b(c);b!=c&&null!=b&&$jscomp.defineProperty(d,a,{configurable:!0,writable:!0,value:b})};
$jscomp.polyfillIsolated=function(a,b,d,c){var f=a.split(".");a=1===f.length;c=f[0];c=!a&&c in $jscomp.polyfills?$jscomp.polyfills:$jscomp.global;for(var l=0;l<f.length-1;l++){var k=f[l];if(!(k in c))return;c=c[k]}f=f[f.length-1];d=$jscomp.IS_SYMBOL_NATIVE&&"es6"===d?c[f]:null;b=b(d);null!=b&&(a?$jscomp.defineProperty($jscomp.polyfills,f,{configurable:!0,writable:!0,value:b}):b!==d&&($jscomp.propertyToPolyfillSymbol[f]=$jscomp.IS_SYMBOL_NATIVE?$jscomp.global.Symbol(f):$jscomp.POLYFILL_PREFIX+f,f=
$jscomp.propertyToPolyfillSymbol[f],$jscomp.defineProperty(c,f,{configurable:!0,writable:!0,value:b})))};$jscomp.initSymbol=function(){};
$jscomp.polyfill("Symbol",function(a){if(a)return a;var b=function(f,l){this.$jscomp$symbol$id_=f;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:l})};b.prototype.toString=function(){return this.$jscomp$symbol$id_};var d=0,c=function(f){if(this instanceof c)throw new TypeError("Symbol is not a constructor");return new b("jscomp_symbol_"+(f||"")+"_"+d++,f)};return c},"es6","es3");$jscomp.initSymbolIterator=function(){};
$jscomp.polyfill("Symbol.iterator",function(a){if(a)return a;a=Symbol("Symbol.iterator");for(var b="Array Int8Array Uint8Array Uint8ClampedArray Int16Array Uint16Array Int32Array Uint32Array Float32Array Float64Array".split(" "),d=0;d<b.length;d++){var c=$jscomp.global[b[d]];"function"===typeof c&&"function"!=typeof c.prototype[a]&&$jscomp.defineProperty(c.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}})}return a},"es6",
"es3");$jscomp.initSymbolAsyncIterator=function(){};$jscomp.iteratorPrototype=function(a){a={next:a};a[Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):$jscomp.arrayIterator(a)};$jscomp.owns=function(a,b){return Object.prototype.hasOwnProperty.call(a,b)};
$jscomp.polyfill("WeakMap",function(a){function b(){if(!a||!Object.seal)return!1;try{var g=Object.seal({}),h=Object.seal({}),m=new a([[g,2],[h,3]]);if(2!=m.get(g)||3!=m.get(h))return!1;m.delete(g);m.set(h,4);return!m.has(g)&&4==m.get(h)}catch(p){return!1}}function d(){}function c(g){var h=typeof g;return"object"===h&&null!==g||"function"===h}function f(g){if(!$jscomp.owns(g,k)){var h=new d;$jscomp.defineProperty(g,k,{value:h})}}function l(g){if(!$jscomp.ISOLATE_POLYFILLS){var h=Object[g];h&&(Object[g]=
function(m){if(m instanceof d)return m;Object.isExtensible(m)&&f(m);return h(m)})}}if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var k="$jscomp_hidden_"+Math.random();l("freeze");l("preventExtensions");l("seal");var n=0,e=function(g){this.id_=(n+=Math.random()+1).toString();if(g){g=$jscomp.makeIterator(g);for(var h;!(h=g.next()).done;)h=h.value,this.set(h[0],h[1])}};e.prototype.set=function(g,h){if(!c(g))throw Error("Invalid WeakMap key");
f(g);if(!$jscomp.owns(g,k))throw Error("WeakMap key fail: "+g);g[k][this.id_]=h;return this};e.prototype.get=function(g){return c(g)&&$jscomp.owns(g,k)?g[k][this.id_]:void 0};e.prototype.has=function(g){return c(g)&&$jscomp.owns(g,k)&&$jscomp.owns(g[k],this.id_)};e.prototype.delete=function(g){return c(g)&&$jscomp.owns(g,k)&&$jscomp.owns(g[k],this.id_)?delete g[k][this.id_]:!1};return e},"es6","es3");$jscomp.MapEntry=function(){};
$jscomp.polyfill("Map",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_MAP||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var e=Object.seal({x:4}),g=new a($jscomp.makeIterator([[e,"s"]]));if("s"!=g.get(e)||1!=g.size||g.get({x:4})||g.set({x:4},"t")!=g||2!=g.size)return!1;var h=g.entries(),m=h.next();if(m.done||m.value[0]!=e||"s"!=m.value[1])return!1;m=h.next();return m.done||4!=m.value[0].x||"t"!=m.value[1]||!h.next().done?!1:!0}catch(p){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var d=new WeakMap,c=function(e){this.data_={};this.head_=k();this.size=0;if(e){e=$jscomp.makeIterator(e);for(var g;!(g=e.next()).done;)g=g.value,this.set(g[0],g[1])}};c.prototype.set=function(e,g){e=0===e?0:e;var h=f(this,e);h.list||(h.list=this.data_[h.id]=[]);h.entry?h.entry.value=g:(h.entry={next:this.head_,previous:this.head_.previous,head:this.head_,key:e,value:g},h.list.push(h.entry),
this.head_.previous.next=h.entry,this.head_.previous=h.entry,this.size++);return this};c.prototype.delete=function(e){e=f(this,e);return e.entry&&e.list?(e.list.splice(e.index,1),e.list.length||delete this.data_[e.id],e.entry.previous.next=e.entry.next,e.entry.next.previous=e.entry.previous,e.entry.head=null,this.size--,!0):!1};c.prototype.clear=function(){this.data_={};this.head_=this.head_.previous=k();this.size=0};c.prototype.has=function(e){return!!f(this,e).entry};c.prototype.get=function(e){return(e=
f(this,e).entry)&&e.value};c.prototype.entries=function(){return l(this,function(e){return[e.key,e.value]})};c.prototype.keys=function(){return l(this,function(e){return e.key})};c.prototype.values=function(){return l(this,function(e){return e.value})};c.prototype.forEach=function(e,g){for(var h=this.entries(),m;!(m=h.next()).done;)m=m.value,e.call(g,m[1],m[0],this)};c.prototype[Symbol.iterator]=c.prototype.entries;var f=function(e,g){var h=g&&typeof g;"object"==h||"function"==h?d.has(g)?h=d.get(g):
(h=""+ ++n,d.set(g,h)):h="p_"+g;var m=e.data_[h];if(m&&$jscomp.owns(e.data_,h))for(e=0;e<m.length;e++){var p=m[e];if(g!==g&&p.key!==p.key||g===p.key)return{id:h,list:m,index:e,entry:p}}return{id:h,list:m,index:-1,entry:void 0}},l=function(e,g){var h=e.head_;return $jscomp.iteratorPrototype(function(){if(h){for(;h.head!=e.head_;)h=h.previous;for(;h.next!=h.head;)return h=h.next,{done:!1,value:g(h)};h=null}return{done:!0,value:void 0}})},k=function(){var e={};return e.previous=e.next=e.head=e},n=0;
return c},"es6","es3");
$jscomp.polyfill("Set",function(a){function b(){if($jscomp.ASSUME_NO_NATIVE_SET||!a||"function"!=typeof a||!a.prototype.entries||"function"!=typeof Object.seal)return!1;try{var c=Object.seal({x:4}),f=new a($jscomp.makeIterator([c]));if(!f.has(c)||1!=f.size||f.add(c)!=f||1!=f.size||f.add({x:4})!=f||2!=f.size)return!1;var l=f.entries(),k=l.next();if(k.done||k.value[0]!=c||k.value[1]!=c)return!1;k=l.next();return k.done||k.value[0]==c||4!=k.value[0].x||k.value[1]!=k.value[0]?!1:l.next().done}catch(n){return!1}}
if($jscomp.USE_PROXY_FOR_ES6_CONFORMANCE_CHECKS){if(a&&$jscomp.ES6_CONFORMANCE)return a}else if(b())return a;var d=function(c){this.map_=new Map;if(c){c=$jscomp.makeIterator(c);for(var f;!(f=c.next()).done;)this.add(f.value)}this.size=this.map_.size};d.prototype.add=function(c){c=0===c?0:c;this.map_.set(c,c);this.size=this.map_.size;return this};d.prototype.delete=function(c){c=this.map_.delete(c);this.size=this.map_.size;return c};d.prototype.clear=function(){this.map_.clear();this.size=0};d.prototype.has=
function(c){return this.map_.has(c)};d.prototype.entries=function(){return this.map_.entries()};d.prototype.values=function(){return this.map_.values()};d.prototype.keys=d.prototype.values;d.prototype[Symbol.iterator]=d.prototype.values;d.prototype.forEach=function(c,f){var l=this;this.map_.forEach(function(k){return c.call(f,k,k,l)})};return d},"es6","es3");var QuestionsTracker=function(a){this.list=[];this.associated=[];this.index=0;this.reset(a)};
QuestionsTracker.prototype.reset=function(a){this.list=a;this.associated=[];for(a=a.length-1;0<=a;a--)this.associated.push(!1);this.index=-1};QuestionsTracker.prototype.markCorrect=function(){this.associated[this.index]=!0};QuestionsTracker.prototype.currentIndex=function(){return this.index};QuestionsTracker.prototype.currentItem=function(){return this.list[this.index]};QuestionsTracker.prototype.next=function(){this.index+1>=this.list.length?this.index=0:this.index++;return this.list[this.index]};
QuestionsTracker.prototype.previous=function(){0>this.index-1?this.index=this.list.length-1:this.index--;return this.list[this.index]};QuestionsTracker.prototype.countTotal=function(){return this.list.length};QuestionsTracker.prototype.countCorrect=function(){return this.associated.filter(function(a){return a}).length};QuestionsTracker.prototype.hasNextFalse=function(){return 0<=this._nextFalseIndex(this.index+1,this.list.length-1,!0)};
QuestionsTracker.prototype.nextFalse=function(){var a=this._nextFalseIndex(this.index+1,this.list.length-1,!0);if(0>a)console.error("Couldn't find a false thing! Fix please");else return this.index=a,this.list[this.index]};QuestionsTracker.prototype._nextFalseIndex=function(a,b,d){b>this.associated.length-1&&(b=this.associated.length-1);for(var c=a;c<=b;c++)if(!this.associated[c])return c;return d?this._nextFalseIndex(0,a,!1):-1};var DataModel=function(a,b){this.countryData=a;this.topoJsonData=b};
DataModel.prototype.getCountryData=function(){return this.countryData};DataModel.prototype.getTopoJsonData=function(){return this.topoJsonData};var ViewController=function(a){this.model=a.model;this.textbox=this.initialized=!1;this.focusedFeature=a.feature;this.questionTracker=a.questionTracker;this.geoGenerator=this.projection=this.g=this.svg=null;this.bufferedScalingDeltas=[];this.bufferedScalingTimeout=null;this.DEFAULT_SCALE=400;this.height=this.width=0;this._init(a)};
ViewController.prototype.getSvg=function(){return this.svg};ViewController.prototype.getG=function(){return this.g};ViewController.prototype.handleBufferedScaling=function(a){var b=this;b.bufferedScalingDeltas.push(a);b.bufferedScalingTimeout||(b.bufferedScalingTimeout=setTimeout(function(){var d=b.bufferedScalingDeltas.reduce(function(f,l){return 0>f+l?-1:1},0),c=b.projection.scale();b._scaleTo(c+c/100*-10*d,50);b.bufferedScalingTimeout=null;b.bufferedScalingDeltas=[]},50))};
ViewController.prototype._calculateUniqueFeatureIdentifier=function(a){return"country-code-"+a.properties.ISO_N3+"-"+a.properties.ADM0_A3};
ViewController.prototype._init=function(a){if(!this.initialized){var b=this,d=a.width;this.width=a.width;var c=a.height;this.height=a.height;this.projection=d3.geoOrthographic().scale(b.DEFAULT_SCALE).translate([d/2,c/2]);this.geoGenerator=d3.geoPath().projection(this.projection);this.svg=d3.select(a.stageId).append("svg").attr("width",d).attr("height",c);this.g=a=this.svg.append("g").style("stroke-width","1.5px");var f=d3.scalePow([0,5E3],[4,50]).exponent(2);this.svg.call(d3.drag().subject(function(){var l=
b.projection.rotate(),k=b.projection.scale();k=f(k);return{x:l[0]*k,y:-l[1]*k}}).on("drag",function(){var l=b.projection.rotate(),k=b.projection.scale();k=f(k);b._rotateTo([d3.event.x/k,-d3.event.y/k,-l[2]])}));this.svg.call(d3.zoom().on("zoom",function(){d3.event.sourceEvent.deltaY&&b.handleBufferedScaling(d3.event.sourceEvent.deltaY)}));a.append("path").datum({type:"Sphere"}).attr("class","water").attr("d",this.getGeoGenerator());d=this.model.getTopoJsonData();d=topojson.feature(d,d.objects.ne_50m_admin_0_countries);
a.selectAll("path.land").data(d.features).enter().append("path").attr("class","land").attr("id",b._calculateUniqueFeatureIdentifier).attr("data-name",function(l){return l.properties.NAME}).attr("d",b.getGeoGenerator).on("click",function(l){l=b.getName(l);b.message("Clicked country is: "+l)});this.initialized=!0}};ViewController.prototype.message=function(a){var b=document.getElementById("message");a?b.innerText=a:b.innerHTML="&nbsp;"};
ViewController.prototype.updateCounts=function(){d3.select("#total-countries").node().innerText=this.questionTracker.countTotal();d3.select("#correct-countries").node().innerText=this.questionTracker.countCorrect()};ViewController.prototype.focusTextBox=function(){setTimeout(function(){var a=document.getElementById("textentry");a.value="";a.focus()},1)};ViewController.prototype.markCorrect=function(){d3.select(this.featureToPathId(this.focusedFeature)).classed("correct",!0)};
ViewController.prototype.highlightFeature=function(a,b){a&&d3.select(this.featureToPathId(a)).classed("focused",b)};ViewController.prototype.featureToPathId=function(a){return"#"+this._calculateUniqueFeatureIdentifier(a)};ViewController.prototype.getProjection=function(){return this.projection};ViewController.prototype.getGeoGenerator=function(){return this.geoGenerator};
ViewController.prototype.getNameVariants=function(a){return"-99"===a.properties.ISO_N3||"036"===a.properties.ISO_N3?[a.properties.NAME,a.properties.ADMIN]:this.model.getCountryData()[a.properties.ISO_N3].names};ViewController.prototype.getName=function(a){return this.getNameVariants(a)[0]};ViewController.prototype.checkGuess=function(a){for(var b=this.getNameVariants(this.focusedFeature),d=b.length-1;0<=d;d--)if(a.toUpperCase()===b[d].toUpperCase())return!0;return!1};
ViewController.prototype._computeNextScale=function(a,b){var d=this.getProjection(),c=this.getGeoGenerator(),f=d.scale(),l=d.rotate();d.rotate(b);d.scale(this.DEFAULT_SCALE);a=c.bounds(a);d.rotate(l);d.scale(f);return.5*this.DEFAULT_SCALE*Math.min(this.width/2/(a[1][0]-a[0][0]),this.height/2/(a[1][1]-a[0][1]))};ViewController.prototype._computeDurationScale=function(a,b){if(a===b)return 0;a=Math.abs(a-b);b=d3.scalePow([0,1E5],[0,8E3]).exponent(.5);a=Math.max(b(a),800);return a=Math.min(a,8E3)};
ViewController.prototype._computeDurationRotate=function(a,b){return Math.max(30*Math.sqrt(Math.pow(b[0]-a[0],2)+Math.pow(b[1]-a[1],2)),800)};ViewController.prototype._rotateTo=function(a,b){b=void 0===b?1E3:b;var d=this.getProjection(),c=this.getGeoGenerator(),f=d.rotate();d3.selectAll("path").transition().attrTween("d",function(l){var k=d3.interpolate(f,a);return function(n){d.rotate(k(n));c.projection(d);return c(l)}}).duration(b)};
ViewController.prototype._scaleTo=function(a,b){b=void 0===b?1E3:b;var d=this.getProjection(),c=this.getGeoGenerator(),f=d.scale();d3.selectAll("path").transition().attrTween("d",function(l){var k=d3.interpolate(f,a);return function(n){d.scale(k(n));c.projection(d);return c(l)}}).duration(b)};
ViewController.prototype._add_interpolaters=function(a,b){b=this._normalizeArray(b);var d=b.reduce(function(c,f){return c+f},0);1!==d&&(console.log("Rounded out interpolator timings."),b[b.length-1]+=1-d);return function(c){for(var f=0,l=0;l<b.length;l++){if(c<=f+b[l])return a[l]((c-f)/b[l]);f+=b[l]}throw"Fractions didn't add up to 1. Only went to: "+f+". Oops. "+c;}};
ViewController.prototype._normalizeArray=function(a){var b=a.reduce(function(d,c){return d+c},0);return a.map(function(d){return d/b})};
ViewController.prototype._getInterpolators=function(a){var b=a.rotate,d=a.nextRotate,c=a.scale,f=a.nextScale;a=this._computeDurationScale(c,f);var l=this._computeDurationRotate(b,d),k=[],n=[],e=[],g=2*this.DEFAULT_SCALE,h=10*this.DEFAULT_SCALE,m=Math.abs(c-this.DEFAULT_SCALE),p=c;m>g&&(p=this.DEFAULT_SCALE,e.push(this._computeDurationScale(c,p)),k.push(d3.interpolate(b,b)),m>h?n.push(d3.scalePow([0,1],[c,p]).exponent(.1)):n.push(d3.interpolate(c,p)));if(180>=Math.abs(b[0]-d[0]))e.push(this._computeDurationRotate(b,
d)),n.push(d3.interpolate(p,p)),k.push(d3.interpolate(b,d));else{c=180;m=Math.abs(c-b[0]);var q=Math.abs(d[0]- -c),r=Math.abs(-c-b[0]),t=Math.abs(d[0]-c);m+q>r+t&&(c=-c,m=r,q=t);m=b[1]+m/(m+q)*(d[1]-b[1]);q=[c,m];e.push(this._computeDurationRotate(b,q));n.push(d3.interpolate(p,p));k.push(d3.interpolate(b,q));q=[-c,m];e.push(this._computeDurationRotate(q,d));n.push(d3.interpolate(p,p));k.push(d3.interpolate(q,d))}b=Math.abs(f-p);b>g&&(e.push(this._computeDurationScale(p,f)),k.push(d3.interpolate(d,
d)),b>h?n.push(d3.scalePow([0,1],[p,f]).exponent(10)):n.push(d3.interpolate(p,f)));d=this._add_interpolaters(n,e);return{rotation:this._add_interpolaters(k,e),scale:d,duration:a+l}};
ViewController.prototype._rotateGlobe=function(a,b,d,c){var f=this.getProjection(),l=this.getGeoGenerator();a=this._getInterpolators({rotate:d,nextRotate:c,scale:a,nextScale:b});var k=a.rotation,n=a.scale;a=a.duration;d3.selectAll("path").transition().attrTween("d",function(e){return function(g){f.rotate(k(g)).scale(n(g));l.projection(f);return l(e)}}).duration(a)};
ViewController.prototype.transitionViewTo=function(a){var b=this.getProjection(),d=b.rotate();b=b.scale();var c=d3.geoCentroid(a);c=[-c[0],-c[1]];a=this._computeNextScale(a,c);this._rotateGlobe(b,a,d,c)};ViewController.prototype.focusOn=function(a){this.highlightFeature(this.focusedFeature,!1);this.focusedFeature=a;this.highlightFeature(this.focusedFeature,!0);this.transitionViewTo(a);this.updateCounts();this.focusTextBox()};
ViewController.prototype.handleSkip=function(){var a=this.questionTracker.currentItem();a=this.getName(a);this.message("That country was: "+a);this.gotoNextQuestion()};ViewController.prototype.gotoNextQuestion=function(){if(this.questionTracker.hasNextFalse()){var a=this.questionTracker.nextFalse();a&&(a=topojson.feature(this.model.getTopoJsonData(),a),this.focusOn(a))}else this.showVictoryScreen()};
ViewController.prototype.handleNextButton=function(){var a=this.questionTracker.currentItem();a=this.getName(a);this.message("That country was: "+a);if(a=this.questionTracker.next())a=topojson.feature(this.model.getTopoJsonData(),a),this.focusOn(a)};ViewController.prototype.handleBackButton=function(){var a=this.questionTracker.currentItem();a=this.getName(a);this.message("That country was: "+a);if(a=this.questionTracker.previous())a=topojson.feature(this.model.getTopoJsonData(),a),this.focusOn(a)};
ViewController.prototype.showVictoryScreen=function(){this.questionTracker.currentItem();this.highlightFeature(this.focusedFeature,!1);this.updateCounts();document.getElementById("textentry").disabled=!0;this.message("You are victorious!");this._scaleTo(250)};ViewController.prototype.restartWith=function(a){var b=this.questionTracker;document.getElementById("textentry").disabled=!1;d3.selectAll(".correct").classed("correct",!1);b.reset(a);this.changeToCountry(b.nextFalse());this.message("")};
ViewController.prototype.handleTextChange=function(){if(d3.event.ctrlKey&&37===d3.event.keyCode)this.handleBackButton();else if(d3.event.ctrlKey&&39===d3.event.keyCode)this.handleNextButton();else if(d3.event.ctrlKey&&38===d3.event.keyCode)this.handleSkip();else{var a=document.getElementById("textentry");this.checkGuess(a.value)&&(a.value="",this.markCorrect(),this.questionTracker.markCorrect(),this.message(""),this.gotoNextQuestion())}};
ViewController.prototype.changeToCountry=function(a){a&&(a=topojson.feature(this.model.getTopoJsonData(),a),this.focusOn(a))};function shuffleArray(a){for(var b=a.length-1;0<b;b--){var d=Math.floor(Math.random()*(b+1)),c=a[b];a[b]=a[d];a[d]=c}}
function setupControls(a,b,d,c){var f=document.getElementById(b);b=document.createElement("option");b.text="All Continents";f.add(b);var l=new Set;a.forEach(function(n){l.add(n.properties.CONTINENT)});l.forEach(function(n){var e=document.createElement("option");e.text=n;f.add(e)});var k=document.getElementById(d);d=a.map(function(n){return c.getName(n)});d.sort();d.forEach(function(n){var e=document.createElement("option");e.text=n;k.add(e)});d3.select("#skipbutton").on("click",function(){c.handleSkip()});
d3.select("#nextbutton").on("click",function(){c.handleNextButton()});d3.select("#backbutton").on("click",function(){c.handleBackButton()});d3.select("#textentry").on("keyup",function(){c.handleTextChange()});d3.select("#restartbutton").on("click",function(){c.restartWith(a)});f.addEventListener("change",function(){var n=f.value,e=a.filter(function(g){return"All Continents"===n?!0:g.properties.CONTINENT===n});c.restartWith(e)});k.addEventListener("change",function(){for(var n=k.value,e,g=a.length-
1;0<=g;g--)if(n==c.getName(a[g])){e=a[g];break}e?c.changeToCountry(e):console.log("Couldn't find that country.")})}
function setupTooltips(a){for(var b in a)tippy(b,{content:a[b],allowHTML:!0});a="<h4>Tips</h4><ul>;<li>See a country's name by clicking on it. It's okay to do this; liberally while learning.</li>;<li>Skip countries you do not know yet, you'll; be shown the name before moving on.</li>;<li>Naming all the countries is a challenge,; you can start by learning each continent separately. Use the; 'Filter by continent' dropdown to get started.</li>;<li>Quickly navigate to a country by using the 'Find country'; dropdown.</li>;</ul>".split(";").reduce(function(d,c){return d+
c},"");tippy("#help_text_button",{trigger:"click",allowHTML:!0,content:a})}
function mainMethod(a){var b=a.dataModel;a=a.stageId;var d=document.getElementById(a),c=d.clientWidth,f=d.clientHeight;d=b.getTopoJsonData().objects.ne_50m_admin_0_countries.geometries.slice(0);shuffleArray(d);var l=new QuestionsTracker(d);b=new ViewController({model:b,stageId:"#"+a,width:c,height:f,questionTracker:l});setupControls(d,"dropdown-filter","country-dropdown",b);setupTooltips({"#nextbutton":"Shortcut: Control + &#8594;","#backbutton":"Shortcut: Control + &#8592;","#skipbutton":"Shortcut: Control + &#8593;"});
a=l.nextFalse();b.changeToCountry(a)}(function(){d3.json("/data/country-data.json").then(function(a){d3.json("/data/ne_50m_admin_0_countries.json").then(function(b){b=new DataModel(a,b);mainMethod({dataModel:b,stageId:"stage"})})})})();
